spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false
    encoding: utf-8
    enabled: true
    prefix: classpath:/static/
    suffix: .html
    
mybatis:
   mapper-locations: classpath:/mappers/*.xml  
   type-aliases-package: com.ymy.xxb.migrat.sso.server.entity
   configuration:
     call-setters-on-nulls: true

     