server:
  port: 10002
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

nacos:
   config:
     # nacos配置命名空间
     namespace: e0dc69bd-e69c-4bdc-a40c-2c86c27d1a21
     # nacos配置服务地址
     server-addr: 192.168.12.119:8848
   discovery:
     server-addr: 192.168.12.119:8848
     
# 是否开启swagger
swagger:
  open: true

logging:
  file: D:\logs\migrat-module-biz-produce\migrat-module-biz-produce.log
  level: 
     root: DEBUG
     # 映入配置文件方式
     #config: ./logback.xml
     
spring:
   redis:
      host: 192.168.12.42
      port: 6379
      password: bly@xxb_o2o_myRedis
      database: 12
      # 连接redis超时时间15s
      timeout: 15000
      # redis失效时间，默认1800s
      expire: 1800
   lettuce:
      pool:
        #最大活跃连接数，默认8
        max-active: 8
        #最大阻塞时间
        max-wait: 15000
        #最大空闲连接，默认8
        max-idle: 8
        # 最小空闲连接数，默认0
        min-idle: 0
        
# shiro session 自定义配置
shiro:
   session:
      # 10min,单位ms
      global-session-timeout: 1800000
      # 10分钟检查一次
      session-validation-interval: 600000

# 踢出用户过滤器      
kickout:
   max-session: 1