spring:
  profiles:
    active: datasource-dev,dev
  
  thymeleaf:
    cache: false
    encoding: utf-8
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
 
mybatis:
   mapper-locations: classpath*:mappers/*.xml
   type-aliases-package: com.ymy.xxb.migrat.module.biz.produce.entity,com.ymy.xxb.migrat.auth.shiro.entity
   configuration:
     call-setters-on-nulls: true
